###  API ĐĂNG KÝ
POST {{url}}/auth/signup
Accept: application/json
Content-Type: application/json

{
   "fullName":"Xuyen",
   "email":"minhxuyen2705@gmail.com",
   "password":"Xuyen2007@",
   "role":"ROLE_RESTAURANT_OWNER"
}


### API ĐĂNG NHẬP

POST {{url}}/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "email":"minhxuyen2705@gmail.com",
  "password":"Xuyen2007@"
}


### API TẠO RESTAURANT.