###  API ĐĂNG KÝ
POST {{url}}/auth/signup
Accept: application/json
Content-Type: application/json

{
   "fullName":"Xuyen",
   "email":"minhxuyen2705@gmail.com",
   "password":"Xuyen2007@",
   "role":"ROLE_RESTAURANT_OWNER"
}


### API ĐĂNG NHẬP

POST {{url}}/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "email":"minhxuyen2705@gmail.com",
  "password":"Xuyen2007@"
}


### API TẠO RESTAURANT.
POST {{url}}/api/admin/restaurants
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Chả ca Ha Noi",
  "description": "Cua Hang Cha Ca Ha Noi",
  "cuisineType": "VietNam",
  "address": {
     "streetAddress": "219 Cau Giay",
      "city": "Ha Noi",
      "stateProvince" : "123",
      "postalCode": "123",
      "country": "VietNam"
  },
  "contactInformation": {
    "email": "xuyentv@gmail.com",
    "mobile": "0334012323",
    "twitter": "",
    "instagram": ""
  },
  "openingHour": "9AM",
  "images": [
    "https://images.pexels.com/photos/2253643/pexels-photo-2253643.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/799879/pexels-photo-799879.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/13457930/pexels-photo-13457930.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
  ]

}


### API get all restaurants

GET {{url}}/api/restaurants
Authorization: Bearer {{jwt}}
Content-Type: application/json

### API admin category

POST {{url}}/api/admin/category
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "burger"
}



### API tao ingredients

POST {{url}}/api/admin/ingredients/category
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "source",
  "restaurantId": 2
}


### API tao

POST {{url}}/api/admin/ingredients
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "white source",
  "restaurantId": 2,
  "categoryId": 1
}


### get ingredients of restaurant

GET {{url}}/api/admin/ingredients/restaurant/2
Authorization: Bearer {{jwt}}
Content-Type: application/json


### tao mon an

POST {{url}}/api/admin/food
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Pizza",
  "description": "Pizza",
  "price": 17,
  "images": [
    "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/428355/pexels-photo-428355.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2876748/pexels-photo-2876748.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
  ],
  "restaurantId": 2,
  "vegetarian": false,
  "seasonal": true,
  "category": {
    "id": 1,
    "name": "Pizza"
  },
  "ingredients": [
    {
      "id":1,
      "name": "white source",
      "category": {
        "id": 1,
        "name": "source"
      },
      "inStoke": true
    }
  ]

}